#!/usr/bin/env bash
set -euo pipefail

# ──────────────────────────────────────────────────────────────
# OpenDex install script
# Generates .env, Radicale htpasswd, starts services.
# If .env already exists, reads existing values and only prompts for missing ones.
# ──────────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# ── Colors ────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

info()  { echo -e "${CYAN}[INFO]${NC}  $*"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
err()   { echo -e "${RED}[ERROR]${NC} $*" >&2; }

# ── Load existing .env ──────────────────────────────────
load_env() {
    if [[ -f .env ]]; then
        info "Found existing .env — loading values"
        set -a
        # shellcheck disable=SC1091
        source <(grep -v '^\s*#' .env | grep -v '^\s*$')
        set +a
    fi
}

# ── Detect OS ─────────────────────────────────────────────────
detect_os() {
    case "$(uname -s)" in
        Linux*)  OS="linux" ;;
        Darwin*) OS="macos" ;;
        CYGWIN*|MINGW*|MSYS*) OS="windows" ;;
        *) OS="unknown" ;;
    esac
    echo "$OS"
}

# ── Check prerequisites ──────────────────────────────────────
check_prereqs() {
    local missing=0

    if ! command -v docker &>/dev/null; then
        err "docker is not installed. Install it from https://docs.docker.com/get-docker/"
        missing=1
    fi

    if ! docker compose version &>/dev/null; then
        err "docker compose v2 is not available. Update Docker or install the compose plugin."
        missing=1
    fi

    if [[ $missing -eq 1 ]]; then
        exit 1
    fi

    ok "docker $(docker --version | awk '{print $3}' | tr -d ',')"
    ok "docker compose $(docker compose version --short)"
}


# ── Write .env ─────────────────────────────────────────────────
write_env() {
    cat > .env <<EOF
# OpenDex configuration (generated by install.sh)

# Domain
DOMAIN=${DOMAIN}
ACME_EMAIL=${ACME_EMAIL}

# Ports
HTTP_PORT=${HTTP_PORT}
HTTPS_PORT=${HTTPS_PORT}

# UI
TRAEFIK_DASHBOARD=${TRAEFIK_DASHBOARD}
RADICALE_WEB_TYPE=${RADICALE_WEB_TYPE}

# PostgreSQL
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# CardDAV (Radicale)
CARDDAV_USER=${CARDDAV_USER}
CARDDAV_PASSWORD=${CARDDAV_PASSWORD}
EOF

    chmod 600 .env
    ok "Written .env"
}

# ── Main ──────────────────────────────────────────────────────
main() {
    echo ""
    echo "═══════════════════════════════════════"
    echo "         OpenDex Installer"
    echo "═══════════════════════════════════════"
    echo ""

    # 1. Detect OS & check prereqs
    OS=$(detect_os)
    info "Detected OS: $OS"
    check_prereqs

    # 2. Load existing config
    load_env

    # 3. Collect configuration (skip already-set values)
    echo ""
    info "Configure your instance (press Enter to accept defaults)"
    echo ""

    prompt_if_unset DOMAIN "Domain" ""
    prompt_if_unset ACME_EMAIL "Let's Encrypt email" ""
    prompt_if_unset HTTP_PORT "HTTP port" "80"
    prompt_if_unset HTTPS_PORT "HTTPS port" "443"
    prompt_if_unset TRAEFIK_DASHBOARD "Enable Traefik dashboard (true/false)" "false"
    prompt_if_unset RADICALE_WEB_TYPE "Radicale web UI (internal/none)" "none"

    echo ""
    warn "Make sure these DNS records point to your server:"
    echo "    ${DOMAIN}             -> your server IP"
    echo "    *.${DOMAIN}           -> your server IP"
    echo ""

    echo ""
    info "PostgreSQL credentials"
    echo ""

    prompt_if_unset POSTGRES_USER "PostgreSQL username" "opendex"
    prompt_if_unset POSTGRES_PASSWORD "PostgreSQL password" "opendex"

    echo ""
    info "CardDAV credentials"
    echo ""

    prompt_if_unset CARDDAV_USER "CardDAV username" "opendex"
    prompt_if_unset CARDDAV_PASSWORD "CardDAV password" ""

    # 4. Create directories
    mkdir -p data/postgres data/radicale data/traefik logs
    chmod 777 logs
    ok "Created data directories"

    # 5. Write .env
    write_env


    # 9. Summary
    echo ""
    echo "═══════════════════════════════════════"
    echo "         OpenDex is running!"
    echo "═══════════════════════════════════════"
    echo ""
    echo -e "  ${GREEN}Radicale Web UI (If Enabled):${NC}   https://radicale.${DOMAIN}"
    echo -e "  ${GREEN}Traefik Web UI (If Enabled):${NC}    https://traefik.${DOMAIN}/dashboard/"
    echo ""
    echo "  CardDAV and CalDAV sync endpoints:"
    echo "    Server:   radicale.${DOMAIN}"
    echo "    Username: ${CARDDAV_USER}"
    echo "    Password: (your CardDAV password)"
    echo ""
    echo "  Credentials saved to .env"
    echo ""
    echo "  To stop:   docker compose down"
    echo "  To start:  docker compose up -d"
    echo "  Logs:      docker compose logs -f"
    echo ""
}

main "$@"
