#!/usr/bin/env bash
set -euo pipefail

# ──────────────────────────────────────────────────────────────
# OpenDex install script
# Generates docker.env, Radicale htpasswd, starts services.
# If docker.env already exists, reads existing values and only prompts for missing ones.
# ──────────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# ── Colors ────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

info()  { echo -e "${CYAN}[INFO]${NC}  $*"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
err()   { echo -e "${RED}[ERROR]${NC} $*" >&2; }

# ── Load existing docker.env ──────────────────────────────────
load_env() {
    if [[ -f docker.env ]]; then
        info "Found existing docker.env — loading values"
        # Export all non-comment, non-empty lines
        set -a
        # shellcheck disable=SC1091
        source <(grep -v '^\s*#' docker.env | grep -v '^\s*$')
        set +a
    fi
}

# ── Detect OS ─────────────────────────────────────────────────
detect_os() {
    case "$(uname -s)" in
        Linux*)  OS="linux" ;;
        Darwin*) OS="macos" ;;
        CYGWIN*|MINGW*|MSYS*) OS="windows" ;;
        *) OS="unknown" ;;
    esac
    echo "$OS"
}

# ── Check prerequisites ──────────────────────────────────────
check_prereqs() {
    local missing=0

    if ! command -v docker &>/dev/null; then
        err "docker is not installed. Install it from https://docs.docker.com/get-docker/"
        missing=1
    fi

    if ! docker compose version &>/dev/null; then
        err "docker compose v2 is not available. Update Docker or install the compose plugin."
        missing=1
    fi

    if [[ $missing -eq 1 ]]; then
        exit 1
    fi

    ok "docker $(docker --version | awk '{print $3}' | tr -d ',')"
    ok "docker compose $(docker compose version --short)"
}

# ── Write docker.env ──────────────────────────────────────────
write_env() {
    cat > docker.env <<EOF
# OpenDex configuration (generated by install.sh)

# Domain
DOMAIN=${DOMAIN}
ACME_EMAIL=${ACME_EMAIL}

# Ports
HTTP_PORT=${HTTP_PORT}
HTTPS_PORT=${HTTPS_PORT}

# CardDAV (Radicale)
CARDDAV_USER=${CARDDAV_USER}
CARDDAV_PASSWORD=${CARDDAV_PASSWORD}
EOF

    chmod 600 docker.env
    ok "Written docker.env"
}

# ── Main ──────────────────────────────────────────────────────
main() {
    echo ""
    echo "═══════════════════════════════════════"
    echo "         OpenDex Installer"
    echo "═══════════════════════════════════════"
    echo ""

    # 1. Detect OS & check prereqs
    OS=$(detect_os)
    info "Detected OS: $OS"
    check_prereqs

    # 2. Load existing config
    load_env

